package Prectice_Exception;

public class AllInOneException {

	public static void main(String[] args) {
		int a=5;
		int b=0;
		int c;
		String name="ram";
		String s=null;

		int arr[]= {1,2,3};
		try {
			c=a/b;
			System.out.println(c);
		} catch ( ArithmeticException e) {
			System.out.println(e);
		}
		try {
			System.out.println(name.charAt(5));
		} catch (StringIndexOutOfBoundsException e) {
			System.out.println(e);
		}
		try {
			System.out.println(s.charAt(3));
		} catch (NullPointerException e) {
			System.out.println(e);
		}
		try {
			System.out.println(arr[9]);
		} catch (Exception e) {
			System.out.println(e);
		}

	}

}
